-- Seed contains ONLY non-tenant reference data. No companies, no brands, no
-- templates — the product ships blank and is populated through onboarding.
--
-- Currently empty: the canvas size catalogue lives in code
-- (SIZE_CATALOG in src/lib/templates/platforms.ts) since 0029, and the
-- product ships no other reference data.
