// The six starter blueprints, transcribed from Appendix A of the seeding
// spec. Geometry, copy, ramps, and slots come from the appendix verbatim —
// nothing here is invented, and nothing here is a literal color or font: the
// materializer resolves every slot per tenant.
//
// Field order is BOTH paint order and member form order. Frame and backer
// shapes (a logo's border, an image slot's surfaceAlt wash) sit immediately
// before the field they decorate so the renderer's DOM-order tiebreak paints
// them underneath; being static, they never reach the member form.
//
// Wrapping: headline-class fields (Display ramps, and the plated CTAs) are
// authored per the appendix with textSizing "shrink" and a minFontSizePx of
// 60% of the ramp size. Note the render pipeline ignores textSizing on
// PLATED fields — a plate hugs its text at the authored size (layout.ts), so
// the CTAs' shrink is stored but inert; long CTA copy grows the pill.

import type { StarterBlueprint, StarterField } from "./types";

type Ramp = Pick<
  StarterField,
  "font" | "fontWeight" | "fontSizePx" | "lineHeight" | "letterSpacingPx" | "uppercase"
>;

/** The Appendix A type ramp. minFontSizePx for shrink fields is 60% of the
 * ramp size, rounded, applied at the use site. */
const RAMP = {
  displayXl: {
    font: "display",
    fontWeight: 600,
    fontSizePx: 140,
    lineHeight: 0.92,
    letterSpacingPx: -4,
  },
  displayL: {
    font: "display",
    fontWeight: 600,
    fontSizePx: 104,
    lineHeight: 0.92,
    letterSpacingPx: -3,
  },
  displayM: {
    font: "display",
    fontWeight: 600,
    fontSizePx: 76,
    lineHeight: 0.94,
    letterSpacingPx: -2.5,
  },
  displayS: {
    font: "display",
    fontWeight: 600,
    fontSizePx: 52,
    lineHeight: 0.98,
    letterSpacingPx: -1.5,
  },
  bodyL: { font: "body", fontWeight: 400, fontSizePx: 34, lineHeight: 1.32, letterSpacingPx: -0.2 },
  bodyM: { font: "body", fontWeight: 400, fontSizePx: 26, lineHeight: 1.36, letterSpacingPx: -0.1 },
  bodyMMedium: {
    font: "body",
    fontWeight: 500,
    fontSizePx: 26,
    lineHeight: 1.32,
    letterSpacingPx: -0.1,
  },
  bodyS: { font: "body", fontWeight: 400, fontSizePx: 20, lineHeight: 1.42, letterSpacingPx: 0 },
  label: {
    font: "label",
    fontWeight: 500,
    fontSizePx: 22,
    lineHeight: 1.0,
    letterSpacingPx: 1.6,
    uppercase: true,
  },
  labelS: {
    font: "label",
    fontWeight: 500,
    fontSizePx: 16,
    lineHeight: 1.0,
    letterSpacingPx: 1.2,
    uppercase: true,
  },
} as const satisfies Record<string, Ramp>;

/** Shrink floor: 60% of the ramp size, rounded. */
const floor = (ramp: Ramp): number => Math.round(ramp.fontSizePx! * 0.6);

/** The tenant logo slot plus its 1px border frame. Strokes are shape-only
 * on this model (types.ts: "Shape fields only"; ImageFieldBox renders none),
 * so the border is a static transparent rect drawn at the same geometry —
 * omitted together with the logo via omitWith. */
const logoSlot = (x: number, y: number, w: number, h: number): StarterField[] => [
  {
    fieldKey: "logo_frame",
    label: "Logo frame",
    type: "shape",
    shape: "rect",
    static: true,
    omitWith: "logo",
    x,
    y,
    width: w,
    height: h,
    strokeColor: "border",
    strokeWidthPx: 1,
  },
  {
    fieldKey: "logo",
    label: "Logo",
    type: "image",
    role: "logo",
    x,
    y,
    width: w,
    height: h,
    objectFit: "contain",
  },
];

/** An editable photo slot over a surfaceAlt wash. The wash is what the
 * appendix's "fill surfaceAlt" means: the slot reads as part of the design
 * before a photo lands, and the Dark variant recolors it. */
const imageSlot = (
  fieldKey: string,
  label: string,
  placeholder: string,
  x: number,
  y: number,
  w: number,
  h: number,
): StarterField[] => [
  {
    fieldKey: `${fieldKey}_bg`,
    label: `${label} backdrop`,
    type: "shape",
    shape: "rect",
    static: true,
    x,
    y,
    width: w,
    height: h,
    colorHex: "surfaceAlt",
  },
  {
    fieldKey,
    label,
    type: "image",
    placeholder,
    x,
    y,
    width: w,
    height: h,
    objectFit: "cover",
  },
];

const productLaunch: StarterBlueprint = {
  starterKey: "launch-01",
  name: "Product launch",
  description: "Announce a launch with a product image, a headline, and a call to action.",
  category: "Announcements",
  tags: ["launch", "product"],
  canvasWidth: 1080,
  canvasHeight: 1350,
  captionTemplate: "{company.name} just launched something new.",
  backgroundColor: "surface",
  fields: [
    ...logoSlot(80, 72, 142, 50),
    {
      fieldKey: "kicker",
      label: "Kicker",
      type: "text",
      static: true,
      staticValue: "Product launch",
      x: 850,
      y: 89,
      width: 150,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
      align: "right",
    },
    ...imageSlot("image", "Product image", "Add a product image", 80, 165, 920, 560),
    {
      fieldKey: "eyebrow",
      label: "Eyebrow",
      type: "text",
      placeholder: "Now available",
      x: 80,
      y: 768,
      width: 920,
      height: 22,
      ...RAMP.label,
      colorHex: "accent",
    },
    {
      fieldKey: "headline",
      label: "Headline",
      type: "multiline",
      placeholder: "The thing your team has been asking for is here.",
      x: 80,
      y: 812,
      width: 920,
      height: 288,
      ...RAMP.displayL,
      colorHex: "ink",
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.displayL),
      verticalAlign: "top",
    },
    {
      fieldKey: "subhead",
      label: "Subhead",
      type: "multiline",
      placeholder: "One sentence on what it does and who it is for. Twenty words or fewer.",
      x: 80,
      y: 1122,
      width: 920,
      height: 35,
      ...RAMP.bodyM,
      colorHex: "inkMuted",
      verticalAlign: "top",
    },
    {
      fieldKey: "cta",
      label: "Call to action",
      type: "text",
      placeholder: "Read the announcement",
      x: 80,
      y: 1200,
      width: 360,
      height: 78,
      ...RAMP.bodyMMedium,
      colorHex: "onAccent",
      plateColor: "accent",
      platePaddingX: 32,
      platePaddingY: 22,
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.bodyMMedium),
      verticalAlign: "top",
    },
    {
      fieldKey: "url",
      label: "Link",
      type: "text",
      static: true,
      staticValue: "{company.website}/launch",
      x: 806,
      y: 1231,
      width: 194,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
      align: "right",
    },
  ],
};

const featureHighlight: StarterBlueprint = {
  starterKey: "feature-02",
  name: "Feature highlight",
  description: "Spotlight one new feature with a big headline and a supporting line.",
  category: "Announcements",
  tags: ["feature", "update"],
  canvasWidth: 1080,
  canvasHeight: 1080,
  captionTemplate: "New in {company.name}: less busywork.",
  backgroundColor: "surface",
  fields: [
    ...logoSlot(80, 72, 142, 50),
    {
      fieldKey: "kicker",
      label: "Kicker",
      type: "text",
      static: true,
      staticValue: "What's new",
      x: 893,
      y: 89,
      width: 107,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
      align: "right",
    },
    {
      fieldKey: "eyebrow",
      label: "Eyebrow",
      type: "text",
      placeholder: "Feature",
      x: 80,
      y: 304,
      width: 920,
      height: 22,
      ...RAMP.label,
      colorHex: "accent",
    },
    {
      fieldKey: "headline",
      label: "Headline",
      type: "multiline",
      placeholder: "Schedule a month of posts without leaving the calendar.",
      x: 80,
      y: 354,
      width: 920,
      height: 142,
      ...RAMP.displayM,
      colorHex: "ink",
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.displayM),
      verticalAlign: "top",
    },
    {
      fieldKey: "subhead",
      label: "Subhead",
      type: "multiline",
      placeholder: "Two lines on what changed and why it matters to the person reading this.",
      x: 80,
      y: 524,
      width: 920,
      height: 90,
      ...RAMP.bodyL,
      colorHex: "inkMuted",
      verticalAlign: "top",
    },
    {
      fieldKey: "rule",
      label: "Rule",
      type: "shape",
      shape: "rect",
      static: true,
      x: 80,
      y: 795,
      width: 920,
      height: 3,
      colorHex: "accent",
    },
    {
      fieldKey: "footnote",
      label: "Footnote",
      type: "text",
      placeholder: "Available to every plan today",
      x: 80,
      y: 980,
      width: 600,
      height: 28,
      ...RAMP.bodyS,
      colorHex: "ink",
    },
    {
      fieldKey: "url",
      label: "Link",
      type: "text",
      static: true,
      staticValue: "{company.website}/whats-new",
      x: 774,
      y: 986,
      width: 226,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
      align: "right",
    },
  ],
};

const companyMilestone: StarterBlueprint = {
  starterKey: "milestone-03",
  name: "Company milestone",
  description: "Mark a milestone with a story headline beside a full-height team photo.",
  category: "Company",
  tags: ["milestone", "story"],
  canvasWidth: 1600,
  canvasHeight: 900,
  captionTemplate: "A milestone worth sharing from {company.name}.",
  backgroundColor: "surface",
  fields: [
    ...logoSlot(80, 72, 142, 50),
    {
      fieldKey: "kicker",
      label: "Kicker",
      type: "text",
      static: true,
      staticValue: "Milestone",
      x: 804,
      y: 89,
      width: 96,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
      align: "right",
    },
    {
      fieldKey: "eyebrow",
      label: "Eyebrow",
      type: "text",
      placeholder: "2019 to 2026",
      x: 80,
      y: 291,
      width: 820,
      height: 22,
      ...RAMP.label,
      colorHex: "accent",
    },
    {
      fieldKey: "headline",
      label: "Headline",
      type: "multiline",
      placeholder: "Seven years of building alongside the teams who use this.",
      x: 80,
      y: 337,
      width: 820,
      height: 213,
      ...RAMP.displayM,
      colorHex: "ink",
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.displayM),
      verticalAlign: "top",
    },
    {
      fieldKey: "subhead",
      label: "Subhead",
      type: "multiline",
      placeholder: "A sentence of context: what the milestone is, and the people who got you here.",
      x: 80,
      y: 574,
      width: 820,
      height: 70,
      ...RAMP.bodyM,
      colorHex: "inkMuted",
      verticalAlign: "top",
    },
    {
      fieldKey: "url",
      label: "Link",
      type: "text",
      static: true,
      staticValue: "{company.website}/story",
      x: 80,
      y: 812,
      width: 183,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
    },
    ...imageSlot("image", "Team photo", "Add a team photo", 980, 0, 620, 900),
  ],
};

const partnershipAnnouncement: StarterBlueprint = {
  starterKey: "partnership-04",
  name: "Partnership announcement",
  description: "Two logos side by side with a shared headline about what comes next.",
  category: "Announcements",
  tags: ["partnership"],
  canvasWidth: 1200,
  canvasHeight: 630,
  captionTemplate: "{company.name} has a new partner.",
  backgroundColor: "surface",
  fields: [
    {
      fieldKey: "eyebrow",
      label: "Eyebrow",
      type: "text",
      placeholder: "Partnership",
      x: 519,
      y: 64,
      width: 162,
      height: 22,
      ...RAMP.label,
      colorHex: "accent",
      align: "center",
    },
    // Both slot frames always ship: a partnership template without its two
    // logo slots is meaningless, so a missing tenant logo leaves this slot
    // editable rather than dropping it (see the materializer).
    {
      fieldKey: "logo_frame",
      label: "Logo frame",
      type: "shape",
      shape: "rect",
      static: true,
      x: 261,
      y: 164,
      width: 300,
      height: 84,
      strokeColor: "border",
      strokeWidthPx: 1,
    },
    {
      fieldKey: "logo",
      label: "Your logo",
      type: "image",
      role: "logo",
      placeholder: "Add your logo",
      x: 261,
      y: 164,
      width: 300,
      height: 84,
      objectFit: "contain",
    },
    {
      fieldKey: "plus",
      label: "Plus",
      type: "text",
      static: true,
      staticValue: "+",
      x: 593,
      y: 195,
      width: 14,
      height: 22,
      ...RAMP.label,
      colorHex: "inkMuted",
    },
    {
      fieldKey: "partner_logo_frame",
      label: "Partner logo frame",
      type: "shape",
      shape: "rect",
      static: true,
      x: 639,
      y: 164,
      width: 300,
      height: 84,
      strokeColor: "border",
      strokeWidthPx: 1,
    },
    {
      fieldKey: "partner_logo",
      label: "Partner logo",
      type: "image",
      placeholder: "Add the partner logo",
      x: 639,
      y: 164,
      width: 300,
      height: 84,
      objectFit: "contain",
    },
    {
      fieldKey: "headline",
      label: "Headline",
      type: "multiline",
      placeholder: "{company.name} and Partner are building something together.",
      x: 72,
      y: 326,
      width: 1056,
      height: 102,
      ...RAMP.displayS,
      colorHex: "ink",
      align: "center",
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.displayS),
      verticalAlign: "top",
    },
    {
      fieldKey: "subhead",
      label: "Subhead",
      type: "multiline",
      placeholder: "One line on what the partnership does for the people reading this.",
      x: 72,
      y: 444,
      width: 1056,
      height: 28,
      ...RAMP.bodyS,
      colorHex: "inkMuted",
      align: "center",
      verticalAlign: "top",
    },
    {
      fieldKey: "url",
      label: "Link",
      type: "text",
      static: true,
      staticValue: "{company.website}/partners",
      x: 493,
      y: 550,
      width: 215,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
      align: "center",
    },
  ],
};

const statHighlight: StarterBlueprint = {
  starterKey: "stat-05",
  name: "Stat highlight",
  description: "Lead with one big number and the line that gives it meaning.",
  category: "Results",
  tags: ["stat", "proof"],
  canvasWidth: 1080,
  canvasHeight: 1080,
  captionTemplate: "The numbers behind {company.name}.",
  backgroundColor: "surface",
  fields: [
    ...logoSlot(80, 72, 142, 50),
    {
      fieldKey: "kicker",
      label: "Kicker",
      type: "text",
      static: true,
      staticValue: "By the numbers",
      x: 850,
      y: 89,
      width: 150,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
      align: "right",
    },
    {
      fieldKey: "eyebrow",
      label: "Eyebrow",
      type: "text",
      placeholder: "Q2 results",
      x: 80,
      y: 336,
      width: 920,
      height: 22,
      ...RAMP.label,
      colorHex: "accent",
    },
    {
      fieldKey: "stat",
      label: "Stat",
      type: "text",
      placeholder: "3.2x",
      x: 80,
      y: 370,
      width: 920,
      height: 129,
      ...RAMP.displayXl,
      colorHex: "ink",
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.displayXl),
    },
    {
      fieldKey: "stat_label",
      label: "Stat label",
      type: "multiline",
      placeholder: "faster from brief to published post",
      x: 80,
      y: 511,
      width: 920,
      height: 102,
      ...RAMP.displayS,
      colorHex: "inkMuted",
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.displayS),
      verticalAlign: "top",
    },
    {
      fieldKey: "rule",
      label: "Rule",
      type: "shape",
      shape: "rect",
      static: true,
      x: 80,
      y: 775,
      width: 920,
      height: 3,
      colorHex: "accent",
    },
    {
      fieldKey: "source",
      label: "Source",
      type: "text",
      placeholder: "Source: internal data, Q2 2026",
      x: 80,
      y: 992,
      width: 500,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
    },
    {
      fieldKey: "url",
      label: "Link",
      type: "text",
      static: true,
      staticValue: "{company.website}",
      x: 882,
      y: 992,
      width: 118,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
      align: "right",
    },
  ],
};

const eventPromo: StarterBlueprint = {
  starterKey: "event-06",
  name: "Event promo",
  description: "A story-sized invitation with the date, time, and a seat-saving call to action.",
  category: "Events",
  tags: ["event", "webinar"],
  canvasWidth: 1080,
  canvasHeight: 1920,
  captionTemplate: "Join {company.name} live.",
  backgroundColor: "surface",
  fields: [
    ...logoSlot(80, 90, 142, 50),
    ...imageSlot("image", "Event photo", "Add a speaker or venue photo", 80, 226, 920, 746),
    {
      fieldKey: "eyebrow",
      label: "Eyebrow",
      type: "text",
      placeholder: "Live webinar",
      x: 80,
      y: 1058,
      width: 920,
      height: 22,
      ...RAMP.label,
      colorHex: "accent",
    },
    {
      fieldKey: "headline",
      label: "Headline",
      type: "multiline",
      placeholder: "How five teams cut their production time in half.",
      x: 80,
      y: 1102,
      width: 920,
      height: 142,
      ...RAMP.displayM,
      colorHex: "ink",
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.displayM),
      verticalAlign: "top",
    },
    {
      fieldKey: "subhead",
      label: "Subhead",
      type: "multiline",
      placeholder: "One line on what attendees will walk away with.",
      x: 80,
      y: 1266,
      width: 920,
      height: 35,
      ...RAMP.bodyM,
      colorHex: "inkMuted",
      verticalAlign: "top",
    },
    {
      fieldKey: "hairline_1",
      label: "Hairline",
      type: "shape",
      shape: "rect",
      static: true,
      x: 80,
      y: 1405,
      width: 920,
      height: 1,
      colorHex: "border",
    },
    {
      fieldKey: "date_label",
      label: "Date label",
      type: "text",
      static: true,
      staticValue: "Date",
      x: 80,
      y: 1423,
      width: 100,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
    },
    {
      fieldKey: "date",
      label: "Date",
      type: "text",
      placeholder: "Thursday, 12 November",
      x: 400,
      y: 1414,
      width: 600,
      height: 35,
      ...RAMP.bodyM,
      colorHex: "ink",
      align: "right",
    },
    {
      fieldKey: "hairline_2",
      label: "Hairline",
      type: "shape",
      shape: "rect",
      static: true,
      x: 80,
      y: 1493,
      width: 920,
      height: 1,
      colorHex: "border",
    },
    {
      fieldKey: "time_label",
      label: "Time label",
      type: "text",
      static: true,
      staticValue: "Time",
      x: 80,
      y: 1511,
      width: 100,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
    },
    {
      fieldKey: "time",
      label: "Time",
      type: "text",
      placeholder: "1:00 PM CT, 45 minutes",
      x: 400,
      y: 1502,
      width: 600,
      height: 35,
      ...RAMP.bodyM,
      colorHex: "ink",
      align: "right",
    },
    {
      fieldKey: "hairline_3",
      label: "Hairline",
      type: "shape",
      shape: "rect",
      static: true,
      x: 80,
      y: 1581,
      width: 920,
      height: 1,
      colorHex: "border",
    },
    {
      fieldKey: "where_label",
      label: "Where label",
      type: "text",
      static: true,
      staticValue: "Where",
      x: 80,
      y: 1599,
      width: 100,
      height: 16,
      ...RAMP.labelS,
      colorHex: "inkMuted",
    },
    {
      fieldKey: "where",
      label: "Where",
      type: "text",
      placeholder: "Online, link sent after signup",
      x: 400,
      y: 1590,
      width: 600,
      height: 35,
      ...RAMP.bodyM,
      colorHex: "ink",
      align: "right",
    },
    {
      fieldKey: "cta",
      label: "Call to action",
      type: "text",
      placeholder: "Save your seat at {company.website}/webinar",
      placeholderNoWebsite: "Save your seat",
      x: 80,
      y: 1737,
      width: 920,
      height: 94,
      ...RAMP.bodyMMedium,
      colorHex: "onAccent",
      plateColor: "accent",
      platePaddingX: 32,
      platePaddingY: 30,
      align: "center",
      textSizing: "shrink",
      minFontSizePx: floor(RAMP.bodyMMedium),
      verticalAlign: "top",
    },
  ],
};

export const STARTER_BLUEPRINTS: readonly StarterBlueprint[] = [
  productLaunch,
  featureHighlight,
  companyMilestone,
  partnershipAnnouncement,
  statHighlight,
  eventPromo,
];
